config/routes.rb
Arvi::Application.routes.draw do
  resources :categories

  resources :guidelines

  match "/guidelines/search/:search" => "guidelines#search", :format => "html"
  match "/guidelines/search.:format/:search" => "guidelines#search"
  match "/guidelines/category/:id" => "guidelines#category", :format => "html"
  match "/guidelines/category.:format/:id" => "guidelines#category"
  
  match "/:platform/guidelines/search/:search" => "guidelines#search", :format => "html"
  match "/:platform/guidelines/search.:format/:search" => "guidelines#search"
  match "/:platform/guidelines/category/:id" => "guidelines#category", :format => "html"
  match "/:platform/guidelines/category.:format/:id" => "guidelines#category"
  
  root :to => "home#index"
  
  get '/cli' => "home#cli"











end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :guidelines
  
  def subcategories
    Category.where(:parentId => id)
  end
end

app/models/guideline.rb
class Guideline < ActiveRecord::Base
  has_and_belongs_to_many :categories
  
  def self.search(search)
    words = search.split(' ')
    conditions = []
    words.each do |word|
      conditions.push('(name LIKE "%' + word + '%" OR description1 LIKE "%' + word + '%")')
    end
    find(:all, :conditions => conditions.join(' AND '))
  end
  
  def profileNames
    names = []
    self.profiles.split(',').each do |profile|
      case profile
      when "20"
        names.push("A") # Astmaattinen tai allerginen
      when "15"
        names.push("AP") # Avustettu pyörätuolin käyttäjä
      when "8"
        names.push("E") # Epävarmasti kävelevä
      when "7"
        names.push("N") # Heikkonäköinen
      when "1"
        names.push("K") # Huonokuuloinen tai kuuro
      when "25"
        names.push("M") # Huonomuistinen
      when "14"
        names.push("IP") # Itsenäinen pyörätuolin käyttäjä
      when "16"
        names.push("T") # Käsien tai ylävartalon toimintarajoitteinen
      when "11"
        names.push("R") # Rollaattorin käyttäjä
      when "3"
        names.push("S") # Sokea
      when "26"
        names.push("Y") # Yleinen
      end
    end
    return names.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.text # index.text.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/guidelines_controller.rb
class GuidelinesController < ApplicationController
  # GET /guidelines
  # GET /guidelines.json
  def index
    @guidelines = Guideline.order("guidelineType").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end
  end

  # GET /guidelines/1
  # GET /guidelines/1.json
  def show
    @guideline = Guideline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guideline }
    end
  end
  
  # GET /guidelines/search/params
  # GET /guidelines/search/params.text
  def search
    @guidelines = Guideline.order("guidelineType").search params[:search]
    
    respond_to do |format|
      format.text
    end
  end
  
  def category
    @guidelines = Guideline.find_by_sql("SELECT guidelines.* FROM guidelines WHERE id IN (SELECT guideline_id FROM categories_guidelines WHERE category_id = " + params[:id] + ") ORDER BY guidelineType ASC")
    @showing_category = params[:id]
    @platform = params[:platform]
    
    respond_to do |format|
      format.html
      format.text
    end
  end

  # GET /guidelines/new
  # GET /guidelines/new.json
  def new
    @guideline = Guideline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guideline }
    end
  end

  # GET /guidelines/1/edit
  def edit
    @guideline = Guideline.find(params[:id])
  end

  # POST /guidelines
  # POST /guidelines.json
  def create
    @guideline = Guideline.new(params[:guideline])

    respond_to do |format|
      if @guideline.save
        format.html { redirect_to @guideline, notice: 'Guideline was successfully created.' }
        format.json { render json: @guideline, status: :created, location: @guideline }
      else
        format.html { render action: "new" }
        format.json { render json: @guideline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guidelines/1
  # PUT /guidelines/1.json
  def update
    @guideline = Guideline.find(params[:id])

    respond_to do |format|
      if @guideline.update_attributes(params[:guideline])
        format.html { redirect_to @guideline, notice: 'Guideline was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @guideline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guidelines/1
  # DELETE /guidelines/1.json
  def destroy
    @guideline = Guideline.find(params[:id])
    @guideline.destroy

    respond_to do |format|
      format.html { redirect_to guidelines_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/guidelines_helper.rb
module GuidelinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_category.html.erb
<% unless category.subcategories.nil? %>
<ul>
<% if locals[:platform] == 'm' %>
<%= render :partial => "categories/msubcategory", :format => "html", :collection => category.subcategories, :locals => locals %>
<% else %>
<%= render :partial => "categories/subcategory", :format => "html", :collection => category.subcategories, :locals => locals %>
<% end %>
</ul>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parentId %><br />
    <%= f.number_field :parentId %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_msubcategory.html.erb
<li>
  <table><tr><td style="vertical-align: middle">
    <% if msubcategory.subcategories.empty? && @showing_category.to_s != msubcategory.id.to_s %><a href="/m/guidelines/category/<%= msubcategory.id %>"><% end %>
    <% if msubcategory.subcategories.empty? %>
    <img src="/assets/tree_arrow.png">
    <% end %>
    <% if msubcategory.subcategories.empty? && @showing_category.to_s != msubcategory.id.to_s %></a><% end %>
  </td><td style="height: 36px; vertical-align: middle;<% if !msubcategory.subcategories.empty? %> font-size: 16px; font-weight: bold;<% end %>">
    <% if msubcategory.subcategories.empty? && @showing_category.to_s != msubcategory.id.to_s %><a href="/m/guidelines/category/<%= msubcategory.id %>"><% end %>
    <% if @showing_category.to_s == msubcategory.id.to_s %><b style="color: #448ccb"><% end %>
      <%= (msubcategory.name + ' ').strip! %>
    <% if @showing_category.to_s == msubcategory.id.to_s %></b><% end %>
    <% if msubcategory.subcategories.empty? && @showing_category.to_s != msubcategory.id.to_s %></a><% end %>
  </td></tr></table>
</li>
<% unless msubcategory.subcategories.empty? %>
<ul>
  <%= render :partial => "categories/msubcategory", :format => "text", :collection => msubcategory.subcategories %>
</ul>
<% end %>

app/views/categories/_subcategory.html.erb
<li>
  <% if subcategory.subcategories.empty? && @showing_category.to_s != subcategory.id.to_s %><a href="/guidelines/category/<%= subcategory.id %>"><% end %>
    <% if subcategory.subcategories.empty? %>
      <% if @showing_category.to_s == subcategory.id.to_s %>
    <img src="/assets/tree_selected.png">
      <% else %>
    <img src="/assets/tree_arrow.png">
      <% end %>
    <% else %>
    <img src="/assets/tree_minus.png">
    <% end %>
    <% if @showing_category.to_s == subcategory.id.to_s %><b style="color: #448ccb"><% end %>
      <%= (subcategory.name + ' ').strip! %>
    <% if @showing_category.to_s == subcategory.id.to_s %></b><% end %>
  <% if subcategory.subcategories.empty? && @showing_category.to_s != subcategory.id.to_s %></a><% end %>
</li>
<% unless subcategory.subcategories.empty? %>
<ul>
  <%= render :partial => "categories/subcategory", :format => "text", :collection => subcategory.subcategories %>
</ul>
<% end %>

app/views/categories/_subcategory.text.erb
<%= "  " * indent %>(<%= subcategory.id %>) <%= (subcategory.name + ' ').strip! %>
<% unless subcategory.subcategories.nil? %><%= render :partial => "categories/subcategory", :format => "text", :collection => subcategory.subcategories, :locals => { :indent => indent + 1 } %><% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="m-category-tree">
  <%= render Category.where(:parentId => nil), :locals => { :platform => 'm' } %>
</div>

app/views/categories/index.text.erb
<% @categories.each do |category| %>
<% if category.parentId.nil? %>
<%= category.name %>
<% unless category.subcategories.nil? %>
<%= render :partial => "categories/subcategory", :format => "text", :collection => category.subcategories, :locals => { :indent => 1 } %>
<% end %>
<% end %>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Parentid:</b>
  <%= @category.parentId %>
</p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Guidelines:</b>
  <%= @category.guidelines.count %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/guidelines/_form.html.erb
<%= form_for(@guideline) do |f| %>
  <% if @guideline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guideline.errors.count, "error") %> prohibited this guideline from being saved:</h2>

      <ul>
      <% @guideline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guidelineType %><br />
    <%= f.number_field :guidelineType %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description1 %><br />
    <%= f.text_field :description1 %>
  </div>
  <div class="field">
    <%= f.label :description2 %><br />
    <%= f.text_field :description2 %>
  </div>
  <div class="field">
    <%= f.label :profiles %><br />
    <%= f.text_field :profiles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guidelines/category.html.erb
<% if @platform == 'm' %>
  <script>
  function filterGuidelines() {
    if ($("#textSearch").val().length == 0) {
      $("#resultsCount").text($("div.m-guideline").show().length)
      return;
    }
    var searchWords = $("#textSearch").val().split(' ');
    var searchMatches = [];
    for (var i in searchWords) {
      if (searchWords[i].length > 1) {
        searchMatches.push(new RegExp(searchWords[i], "i"));
      }
    }
    var resultsCount = 0;
    $("div.m-guideline").each(function() {
      var searchableText = "";
      $(this).find("div.m-guideline-name").each(function() {
        searchableText += $(this).text() + " ";
      });
      $(this).find("p").each(function() {
        searchableText += $(this).text() + " ";
      });
      var showThis = true;
      for (var i in searchMatches) {
        if (!searchableText.match(searchMatches[i])) {
          showThis = false;
          break;
        }
      }
      if (showThis) {
        resultsCount++;
        $(this).show();
      } else {
        $(this).hide();
      }
    });
    $("#resultsCount").text(resultsCount);
  }
  
  $(function() {
    $("#resultsCount").text($("div.m-guideline").length)
  });
  </script>

  <div style="position: fixed; top: 0px; left: 0px; width: 100%; height: 40px">
    <div class="m-search-tab" style="height: 40px">
      <table style="width: 100%">
        <tr>
          <td style="vertical-align: middle; text-align: left"><a href="/categories"><img src="/assets/arrow_left.png" style="width: 32px; height: 32px;"></a></td>
          <td style="vertical-align: middle; text-align: center"><input id="textSearch" class="big" style="width: 80%; float: left" onkeyup="filterGuidelines()"></td>
          <td style="vertical-align: middle; text-align: center"><span class="result-count" id="resultsCount"></span></td>
        </tr>
      </table>
    </div>
  </div>
  
  <div style="width: 100%; height: 60px;">&nbsp;</div>
  
  <% @guidelines.each do |guideline| %>
  <div class="m-section m-guideline">
    <% for i in 1..guideline.guidelineType do %>
    <img style="width: 32px; height: 32px; float: left; margin-right: 10px; margin-bottom: 10px;" src="/assets/star.png">
    <% end %>
  
    <div class="guideline-profiles">
    <% guideline.profiles.split(',').each do |profile| %>
      <img style="width: 32px; height: 32px; float: right; margin-left: 10px; margin-bottom: 10px;" src="/assets/profile_<%= profile %>.png">
    <% end %>
    </div>
  
    <div class="m-guideline-name">
      <%= guideline.name %>
    </div>
    
    <hr class="guideline-divider">
    
    <% unless guideline.description1.nil? %>
    <p style="width: 100%; float: left">
      <%= guideline.description1 %>
    </p>
    <% end %>
    
    <% unless guideline.description2.nil? %>
    <p style="width: 100%; float: left">
      <%= guideline.description2 %>
    </p>
    <% end %>
  </div>
  <% end %>
<% else %>
<script>
function filterGuidelines() {
  if ($("#textSearch").val().length == 0) {
    $("#resultsCount").text($("div.guideline").show().length)
    return;
  }
  var searchWords = $("#textSearch").val().split(' ');
  var searchMatches = [];
  for (var i in searchWords) {
    if (searchWords[i].length > 1) {
      searchMatches.push(new RegExp(searchWords[i], "i"));
    }
  }
  var resultsCount = 0;
  $("div.guideline").each(function() {
    var searchableText = "";
    $(this).find("div.guideline-name").each(function() {
      searchableText += $(this).text() + " ";
    });
    $(this).find("p").each(function() {
      searchableText += $(this).text() + " ";
    });
    var showThis = true;
    for (var i in searchMatches) {
      if (!searchableText.match(searchMatches[i])) {
        showThis = false;
        break;
      }
    }
    if (showThis) {
      resultsCount++;
      $(this).show();
    } else {
      $(this).hide();
    }
  });
  $("#resultsCount").text(resultsCount);
}

$(function() {
  $("#resultsCount").text($("div.guideline").length)
});
</script>

<div class="category-tree-wrap-outer">
  <div class="category-tree-wrap-inner">
    <div class="category-tree">
      <%= render Category.where(:parentId => nil), :template => 'categories/index', :locals => { :platform => 'd' } %>
    </div>
  </div>
</div>

<div style="position: fixed; top: 0px; width: 100%">
  <div class="search-tab">
    <table style="width: 100%">
      <tr>
        <td style="vertical-align: middle; text-align: right; width: 200px; font-size: 18px">Tekstisuodatin:</td>
        <td style="vertical-align: middle; text-align: center; width: 400px"><input id="textSearch" class="big" style="width: 100%; float: left" onkeyup="filterGuidelines()"></td>
        <td style="vertical-align: middle; text-align: left; padding-left: 20px;"><span class="result-count" id="resultsCount"></span></td>
      </tr>
    </table>
  </div>
</div>

<div style="width: 100%; height: 60px;">&nbsp;</div>

<% @guidelines.each do |guideline| %>
<div class="section guideline">
  <% for i in 1..guideline.guidelineType do %>
  <img style="width: 48px; height: 48px; float: left; margin-right: 10px; margin-bottom: 10px;" src="/assets/star.png">
  <% end %>

  <div class="guideline-profiles">
  <% guideline.profiles.split(',').each do |profile| %>
    <img style="width: 48px; height: 48px; float: right; margin-left: 10px; margin-bottom: 10px;" src="/assets/profile_<%= profile %>.png">
  <% end %>
  </div>

  <div class="guideline-name">
    <%= guideline.name %>
  </div>
  
  <hr class="guideline-divider">
  
  <% unless guideline.description1.nil? %>
  <p style="width: 100%; float: left">
    <%= guideline.description1 %>
  </p>
  <% end %>
  
  <% unless guideline.description2.nil? %>
  <p style="width: 100%; float: left">
    <%= guideline.description2 %>
  </p>
  <% end %>
</div>
<% end %>
<% end %>

app/views/guidelines/category.text.erb
<% @guidelines.each do |guideline| %>
<%= guideline.name %> [<%= guideline.profileNames %>]
  <% unless guideline.description1.nil? %>
    <%= guideline.description1 %> 
  <% end %>
  <% unless guideline.description2.nil? %>
    <%= guideline.description2 %> 
  <% end %>
  
<% end %>

app/views/guidelines/edit.html.erb
<h1>Editing guideline</h1>

<%= render 'form' %>

<%= link_to 'Show', @guideline %> |
<%= link_to 'Back', guidelines_path %>

app/views/guidelines/index.html.erb
<% @guidelines.each do |guideline| %>
<div class="section guideline">
  <% for i in 1..guideline.guidelineType do %>
  <img style="width: 64px; height: 64px; float: left; margin-right: 10px; margin-bottom: 10px;" src="/assets/star.png">
  <% end %>

  <div class="guideline-profiles">
  <% guideline.profiles.split(',').each do |profile| %>
    <img style="width: 64px; height: 64px; float: right; margin-left: 10px" src="/assets/profile_<%= profile %>.png">
  <% end %>
  </div>

  <div class="guideline-name">
    <%= guideline.name %>
  </div>
  
  <hr class="guideline-divider">
  
  <% unless guideline.description1.nil? %>
  <p style="width: 100%; float: left">
    <%= guideline.description1 %>
  </p>
  <% end %>
  
  <% unless guideline.description2.nil? %>
  <p style="width: 100%; float: left">
    <%= guideline.description2 %>
  </p>
  <% end %>
</div>
<% end %>

app/views/guidelines/new.html.erb
<h1>New guideline</h1>

<%= render 'form' %>

<%= link_to 'Back', guidelines_path %>

app/views/guidelines/search.html.erb
<% @guidelines.each do |guideline| %>
<%= guideline.name %> [<%= guideline.profiles %>]
  <% unless guideline.description1.nil? %>
  <%= guideline.description1 %> 
  <% end %>
  <% unless guideline.description2.nil? %>
  <%= guideline.description2 %> 
  <% end %>
<% end %>

app/views/guidelines/search.text.erb
<% @guidelines.each do |guideline| %>
<%= guideline.name %> [<%= guideline.profileNames %>]
  <% unless guideline.description1.nil? %>
    <%= guideline.description1 %> 
  <% end %>
  <% unless guideline.description2.nil? %>
    <%= guideline.description2 %> 
  <% end %>
  
<% end %>

app/views/guidelines/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section">
  <%= link_to image_tag("arrow_up.png"), guidelines_path %>
</div>

<div class="section guideline">
  <% for i in 1..@guideline.guidelineType do %>
  <img style="width: 64px; height: 64px; float: left; margin-right: 10px; margin-bottom: 10px;" src="/assets/star.png">
  <% end %>

  <div class="guideline-profiles">
  <% @guideline.profiles.split(',').each do |profile| %>
    <img style="width: 64px; height: 64px; float: right; margin-left: 10px" src="/assets/profile_<%= profile %>.png">
  <% end %>
  </div>

  <div class="guideline-name">
    <%= @guideline.name %>
  </div>
  
  <hr class="guideline-divider">
  
  <% unless @guideline.description1.nil? %>
  <p style="width: 100%; float: left">
    <%= @guideline.description1 %>
  </p>
  <% end %>
  
  <% unless @guideline.description2.nil? %>
  <p style="width: 100%; float: left">
    <%= @guideline.description2 %>
  </p>
  <% end %>
</div>

app/views/home/cli.html.erb
<style>
div#input {
  width: 100%;
  float: left;
  font-family: Courier, monospace;
  font-weight: bold;
}

div#output {
  width: 100%;
  float: left;
  font-family: Courier, monospace;
}

pre {
  padding: 0;
  margin: 0;
  width: 100%;
  background: none;
  font-family: Courier, monospace;
  font-size: 12px;
}

@-webkit-keyframes resize {
  0% {
    background-color: rgba(100,100,100,0.2);
  }
  100% {
    background-color: rgba(100,100,100,0.9);
  }
}
@-moz-keyframes resize {
  0% {
    background-color: rgba(100,100,100,0.2);
  }
  100% {
    background-color: rgba(100,100,100,0.9);
  }
}
@-ms-keyframes resize {
  0% {
    background-color: rgba(100,100,100,0.2);
  }
  100% {
    background-color: rgba(100,100,100,0.9);
  }
}

span#cursor {
  display: inline;
  
  -webkit-animation-name: resize;
  -webkit-animation-duration: 0.5s;
  -webkit-animation-iteration-count: infinite;
  -webkit-animation-direction: alternate; 
  
  -moz-animation-name: resize;
  -moz-animation-duration: 0.5s;
  -moz-animation-iteration-count: infinite;
  -moz-animation-direction: alternate;  
  
  -ms-animation-name: resize;
  -ms-animation-duration: 0.5s;
  -ms-animation-iteration-count: infinite;
  -ms-animation-direction: alternate; 
  
  background-color: rgba(100,100,100,0.9);
}
</style>
<script>
var validInput = new RegExp("[a-zA-Z0-9 -]");

function showHelp() {
  $("#output").text($("#output").text() + $("#helpHolder").text());
  window.scroll(0,$("#input").offset().top);
}

function showError(errorString) {
  $("#output").html($("#output").html() + errorString +"\n\n");
  window.scroll(0,$("#input").offset().top);
}

function search(searchPhrase) {
  $.ajax({
    type: 'GET',
    url: '/guidelines/search.text/'+searchPhrase,
    cache: false,
    success: function(result) {
      $("#output").html($("#output").html() + result + "\n");
      window.scroll(0,$("#input").offset().top);
    },
    error: function() {
      showError("connection error");
    }
  });
}

function showCategories() {
  $.ajax({
    type: 'GET',
    url: '/categories.text',
    cache: false,
    success: function(result) {
      $("#output").html($("#output").html() + result + "\n");
      window.scroll(0,$("#input").offset().top);
    },
    error: function() {
      showError("connection error");
    }
  });
}

function listCategory(categoryNumber) {
  $.ajax({
    type: 'GET',
    url: '/guidelines/category.text/'+categoryNumber,
    cache: false,
    success: function(result) {
      $("#output").html($("#output").html() + result + "\n");
      window.scroll(0,$("#input").offset().top);
    },
    error: function() {
      showError("connection error");
    }
  });
}

$(document).keydown(function(e) {
  var code = (e.keyCode ? e.keyCode : e.which);
  if (code == 8){ // Backspace
    $("#inputText").text($("#inputText").text().substr(0, $("#inputText").text().length - 1));
  } else if (code == 13) { // Enter
    var inputString = $("#inputText").text();
    $("#output").html($("#output").html() + inputString +"\n");
    $("#inputText").text("");
    var words = inputString.split(" ");
    if (words.length == 0) return;
    if (words[0] == "clear") {
      $("#output").empty();
    } else if (words[0] == "help") {
      showHelp();
    } else if (words[0] == "search") {
      if (words.length < 2) {
        showError("No search phrase given.");
      } else {
        console.log(words.slice(1).join(' '));
        search(words.slice(1).join(' '));
      }
    } else if (words[0] == "categories") {
      showCategories();
    } else if (words[0] == "list") {
      if (words.length < 2) {
        showError("No category number given.");
      } else {
        listCategory(words[1]);
      }
    } else {
      showError("Unknown command: '"+words[0]+"'");
    }
  } else {
    var c = String.fromCharCode(e.which);
    if (c.length == 1 && c.match(validInput)) {
      $("#inputText").text($("#inputText").text() + (e.shiftKey ? c : c.toLowerCase()));
    }
  }
  return false;
});

$(function() {
  showHelp();
});
</script>
<pre id="helpHolder" style="display: none">
Commands:
  clear
    Clears the screen.
  help
    Shows this help.
  search [search phrases]
    Searches for guidelines using text match on name and description
  categories
    Lists categories
  list [category number]
    Lists guidelines in category

</pre>
<pre id="output">
Welcome to the command line version of Lind, an ARVI accessibility guideline service!

</pre>
<div id="input">
  <span id="inputText"></span><span id="cursor">&nbsp;</span>
</div>

app/views/home/index.html.erb
<div class="section">
  <h1>Lind</h1>
  <h3>An ARVI accessibility guideline service</h3>
  <br><br>
  <a href="/cli" style="font-size: 18px">Command line interface</a>
  <br><br>
  <a href="/guidelines/category/3" style="font-size: 18px">Browse on desktop</a>
  <br><br>
  <a href="/m/guidelines/category/3" style="font-size: 18px">Browse on mobile</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lind</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<img src="/assets/arvi_bg.jpg" style="position: fixed; top: 0px; right: 0px; height: 100%; z-index: -1; opacity: 0.4">

<%= yield %>

</body>
</html>